### PR TITLE
use MIDDLEWARE instead MIDDLEWARE_CLASSES in README, replace deprecated dropin

### PR DESCRIPTION
**Pull request by devkral**
use MIDDLEWARE instead  MIDDLEWARE_CLASSES in documentation.
add django 2 compatibility by replacing Mixin.
TODO: write test for __call__, add stub get_response in tests

### CODE REVIEW

**Comment by tclancy** [comment]
Looks good. Should I wait for the tests?

**Comment by tclancy** [comment]
@devkral - is this good to go or are you still adding tests?

**Comment by devkral** [comment]
sry, not seen. Will add some.

**Comment by tclancy** [comment]
Fantastic, thanks. This actually dovetails nicely with an additional test I need to add. Thanks.

**Comment by devkral** [comment]
rebased version

**Comment by devkral** [comment]
and I fixed the bug, that the unit tests were not executed if called directly

**Pull request merged**
