### PR TITLE
Implement thread safety changes for cached_request_body and multipart…

### PR DESCRIPTION
**Pull request by martinbertolino**
…_boundary, updated tests, and bump version.

@famousfilm Please review this PR to address the issue reported at [https://github.com/Rhumbix/django-request-logging/issues/142]

Summary of the changes:

self.boundary and self.cached_request_body could be overwritten by another thread (in a busy system) before they are actually used, hence showing the incorrect values belonging to a different thread.

I addressed this by removing them from being instance variables and are now locals to the method that previously initialized them.  This caused some changes to some method signatures in order to push down the local values from the members that initialize them.

I also updated the tests to accommodate the new signature for process_request.  All 43 tests passed before the change and after the change.

Two other approaches for this change would have been to:

* Introduce the thread local storage.  Seemed too low level.
* Add some additional member to the request instance.  It did not seem right mutating an instance that we do not 'own'

The implementation approach seemed clearer and followed some FP principles of creating functions/members what get everything they need through their arguments.

I have also tested this with our Django backend system and everything checks out and all of our unit tests pass as well.

I'm seeing some warnings when running the tests related to the changes in Django 4.X.  I did not address those, however I can take a look and propose the changes in a different PR.

```
python3 tests.py
/home/marti/code/django-request-logging/test_urls.py:65: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
  url(r"^somewhere$", general_resource),
/home/marti/code/django-request-logging/test_urls.py:66: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
  url(r"^test_class$", TestView.as_view()),
/home/marti/code/django-request-logging/test_urls.py:67: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
  url(r"^test_func$", view_func),
/home/marti/code/django-request-logging/test_urls.py:68: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
  url(r"^test_msg$", view_msg),
/home/marti/code/django-request-logging/test_urls.py:69: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
  url(r"^dont_log_empty_response_body$", dont_log_empty_response_body),
/home/marti/code/django-request-logging/test_urls.py:70: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
  url(r"^dont_log_silent$", dont_log_silent),
.../home/marti/code/django-request-logging/test_urls_alternate.py:12: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
  url(r"^test_route$", view_func),
........................................
----------------------------------------------------------------------
Ran 43 tests in 0.083s

OK

```

Finally, I had left you a message before on this, for GET requests, the middleware usually logs and empty line like so:

```
INFO|L|2022-01-22 21:04:59,072|1316|139640627201856|aad4804e-3ef0-4f00-b359-2abb309e3884|middleware|log|GET /api/v2/payment_methods/
DEBUG|L|2022-01-22 21:04:59,072|1316|139640627201856|aad4804e-3ef0-4f00-b359-2abb309e3884|middleware|log|{'Cookie': '', 'Content-Type': 'application/octet-stream'}
>>>DEBUG|L|2022-01-22 21:04:59,073|1316|139640627201856|aad4804e-3ef0-4f00-b359-2abb309e3884|middleware|log|b'' <<<
INFO|L|2022-01-22 21:04:59,074|1316|139640627201856|aad4804e-3ef0-4f00-b359-2abb309e3884|middleware|log|GET /api/v2/payment_methods/ - 200
DEBUG|L|2022-01-22 21:04:59,074|1316|139640627201856|aad4804e-3ef0-4f00-b359-2abb309e3884|middleware|log|{'Content-Type': 'application/json', 'Allow': 'GET, HEAD, OPTIONS'}
DEBUG|L|2022-01-22 21:04:59,074|1316|139640627201856|aad4804e-3ef0-4f00-b359-2abb309e3884|middleware|log|b'{"status":200,"data":[...redacted...

```

Some previous version avoided this by testing if the body is an empty bytearray/string.  Should we include that check again to avoid the empty log line?

This could be done in middleware.py line 207 (in this PR) by changing:

if cached_request_body is not None:

to:

if cached_request_body is not None and cached_request_body:

Let me know what you think.

Thank you.

### CODE REVIEW

**Comment by martinbertolino** [comment]
After I created this PR, I was then worried that I had changed the signature of process request so I was revisiting my changes to determine if I missed something.  Reading [this](https://github.com/django/deps/blob/main/final/0005-improved-middleware.rst ) and [this](https://docs.djangoproject.com/en/3.2/topics/http/middleware/) I think the change is good because the class is still a callable.  However, I'm not sure what is your policy or thought in supporting older Django versions and whether this change will break in those older versions, I only tested with Django 3.2.11 and 3.2.4.  If this is important to you, I can revisit the change, however given that self.cached_request_body was initialized in __call__, a direct call to process_request or process_response would definitely now work as expected because self.cached_request_body was not properly initialized.  Perhaps if you are OK with this change, we can also update the names of process_request and process_response so there is no change of being called from outside the class.

**Review by famousfilm — APPROVED** [review]

**Comment by famousfilm** [comment]
Looks fine. 👍 Merged and published. Thanks for contributing @martinbertolino.

**Comment by martinbertolino** [comment]
Fantastic, thank you.  I see the new version out in https://pypi.org/project/django-request-logging/

**Comment by stephappiah** [comment]
fixes #142

**Pull request merged**
